---
title: "Solutions"
output: html_document
date: "2025-05-10"
---

Challenge 1

```{r, echo=TRUE}
# Create 
sample_id = c("sample1", "sample2", "sample3", "sample4")
CFU = c(20, 200, 2000, 3000)
Control = c(TRUE, FALSE, FALSE, FALSE)
Date = c('2025-03-03', '2025-03-04', '2025-03-05', '2025-03-06')

my_first_data_frame <- data.frame(
  sample_id = sample_id,
  CFU = CFU,
  Control = Control,
  Date = as.Date(Date)
)
my_first_data_frame$CFU_multiplied <- my_first_data_frame$CFU*100

str(my_first_data_frame)
saveRDS(my_first_data_frame, "my_first_data_frame.RDS")
```

Challenge 3
```{r}
library(readxl) 
tomato <- read_xlsx('data/Rocio_tomato_modified.xlsx',
                    sheet = 2)

for (j in unique(tomato$Infection)) {
  for (i in unique(tomato$rep)) {
    
    mean_value <- mean(
      tomato$chlorotic.area[tomato$rep == i & 
                              tomato$Infection ==j]
      )

    message("Mean chlorotic area (", i, ", " , j, "): ", 
            round(mean_value,2), " pixels")
  }
}

```


Challenge 5

```{r}
ggplot(tomato_mdf,
       aes(x = Treatment, y = prop_area, fill = Treatment)) +
  geom_violin() +
  geom_jitter(aes(shape = rep), width = 0.2, colour = 'grey', size = 3) +
  facet_wrap(~Infection) +
  scale_fill_manual(values = c('darkred', 'midnightblue')) +
  theme_minimal()
```